---
site_name: 'RESF Docs'
site_url: 'https://rldocs.hbjy.dev'
docs_dir: 'docs'
repo_url: https://github.com/hbjydev/my-rldocs
repo_name: resf/docs
edit_uri: 'edit/main/docs/'

theme:
  name: material
  custom_dir: theme
  features:
    - navigation.tabs.sticky
    - navigation.tabs
    - navigation.top
    - navigation.indexes
  font:
    text: Red Hat Text
  logo: "https://raw.githubusercontent.com/rocky-linux/documentation/main/docs/assets/logo.png"
  favicon: "https://raw.githubusercontent.com/rocky-linux/documentation/main/docs/assets/logo.png"
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: black
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: black

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tabbed
  - footnotes
  - def_list
  - pymdownx.tasklist
  - meta

plugins:
  - search
  - localsearch
  - awesome-pages

extra: 
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/rocky_linux
    - icon: fontawesome/brands/github
      link: https://github.com/rocky-linux
    - icon: fontawesome/brands/gitlab
      link: https://git.rockylinux.org
    - icon: material/home
      link: https://rockylinux.org

copyright: Copyright &copy; 2021 The Rocky Enterprise Software Foundation

